### PR TITLE
Fixes segfaults in VTK output

### PR DESCRIPTION
**Pull request by ddement**

### CODE REVIEW

**Comment by faisal-bhuiyan** [comment]
Did you have a chance to look at an output on Paraview (from any of the regression tests) to make sure things look good there?

**Comment by ddement** [comment]
> Did you have a chance to look at an output on Paraview (from any of the regression tests) to make sure things look good there?

I did not - I was hoping you could really quick.  If you're busy now, I'll get on a remote desktop and try it.

**Comment by faisal-bhuiyan** [comment]
> > Did you have a chance to look at an output on Paraview (from any of the regression tests) to make sure things look good there?
> 
> I did not - I was hoping you could really quick. If you're busy now, I'll get on a remote desktop and try it.

I ran an output from a rotor test (RotorTest.IEA15Rotor) and noticed it was not moving after running it for 1 s. I would expect it to be moving by then.

**Comment by ddement** [comment]
> > > Did you have a chance to look at an output on Paraview (from any of the regression tests) to make sure things look good there?
> > 
> > 
> > I did not - I was hoping you could really quick. If you're busy now, I'll get on a remote desktop and try it.
> 
> I ran an output from a rotor test (RotorTest.IEA15Rotor) and noticed it was not moving after running it for 1 s. I would expect it to be moving by then.

Ok.  I fixed the problem - I was setting the point to qp_x0 always, not qp_x.  I am able to visualize it rotating here on my machine (IEA15RotorHub, 10 seconds).

**Review by faisal-bhuiyan — APPROVED** [review]
Looks good

**Pull request merged**
